// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: nakji/data/market/v1beta1/open_interest.proto

package market

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenInterest defines Open Interest data
type OpenInterest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts                *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`       // [time_series=true]
	Asset             string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"` // contract name or margin asset name
	OpenInterest      *decimal.Decimal       `protobuf:"bytes,3,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	OpenInterestValue *decimal.Decimal       `protobuf:"bytes,4,opt,name=open_interest_value,json=openInterestValue,proto3" json:"open_interest_value,omitempty"`
}

func (x *OpenInterest) Reset() {
	*x = OpenInterest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nakji_data_market_v1beta1_open_interest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenInterest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenInterest) ProtoMessage() {}

func (x *OpenInterest) ProtoReflect() protoreflect.Message {
	mi := &file_nakji_data_market_v1beta1_open_interest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenInterest.ProtoReflect.Descriptor instead.
func (*OpenInterest) Descriptor() ([]byte, []int) {
	return file_nakji_data_market_v1beta1_open_interest_proto_rawDescGZIP(), []int{0}
}

func (x *OpenInterest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OpenInterest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *OpenInterest) GetOpenInterest() *decimal.Decimal {
	if x != nil {
		return x.OpenInterest
	}
	return nil
}

func (x *OpenInterest) GetOpenInterestValue() *decimal.Decimal {
	if x != nil {
		return x.OpenInterestValue
	}
	return nil
}

var File_nakji_data_market_v1beta1_open_interest_proto protoreflect.FileDescriptor

var file_nakji_data_market_v1beta1_open_interest_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6e, 0x61, 0x6b, 0x6a, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x19, 0x6e, 0x61, 0x6b, 0x6a, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x0c, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x39, 0x0a, 0x0d, 0x6f, 0x70, 0x65,
	0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x13, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x11, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x6b, 0x6a, 0x69, 0x2d, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x6b, 0x6a, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x3b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nakji_data_market_v1beta1_open_interest_proto_rawDescOnce sync.Once
	file_nakji_data_market_v1beta1_open_interest_proto_rawDescData = file_nakji_data_market_v1beta1_open_interest_proto_rawDesc
)

func file_nakji_data_market_v1beta1_open_interest_proto_rawDescGZIP() []byte {
	file_nakji_data_market_v1beta1_open_interest_proto_rawDescOnce.Do(func() {
		file_nakji_data_market_v1beta1_open_interest_proto_rawDescData = protoimpl.X.CompressGZIP(file_nakji_data_market_v1beta1_open_interest_proto_rawDescData)
	})
	return file_nakji_data_market_v1beta1_open_interest_proto_rawDescData
}

var file_nakji_data_market_v1beta1_open_interest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nakji_data_market_v1beta1_open_interest_proto_goTypes = []interface{}{
	(*OpenInterest)(nil),          // 0: nakji.data.market.v1beta1.OpenInterest
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*decimal.Decimal)(nil),       // 2: google.type.Decimal
}
var file_nakji_data_market_v1beta1_open_interest_proto_depIdxs = []int32{
	1, // 0: nakji.data.market.v1beta1.OpenInterest.ts:type_name -> google.protobuf.Timestamp
	2, // 1: nakji.data.market.v1beta1.OpenInterest.open_interest:type_name -> google.type.Decimal
	2, // 2: nakji.data.market.v1beta1.OpenInterest.open_interest_value:type_name -> google.type.Decimal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nakji_data_market_v1beta1_open_interest_proto_init() }
func file_nakji_data_market_v1beta1_open_interest_proto_init() {
	if File_nakji_data_market_v1beta1_open_interest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nakji_data_market_v1beta1_open_interest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenInterest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nakji_data_market_v1beta1_open_interest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nakji_data_market_v1beta1_open_interest_proto_goTypes,
		DependencyIndexes: file_nakji_data_market_v1beta1_open_interest_proto_depIdxs,
		MessageInfos:      file_nakji_data_market_v1beta1_open_interest_proto_msgTypes,
	}.Build()
	File_nakji_data_market_v1beta1_open_interest_proto = out.File
	file_nakji_data_market_v1beta1_open_interest_proto_rawDesc = nil
	file_nakji_data_market_v1beta1_open_interest_proto_goTypes = nil
	file_nakji_data_market_v1beta1_open_interest_proto_depIdxs = nil
}
